# Generated by Django 5.2 on 2025-11-01 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='До 9 символов.', max_length=9, unique=True)),
                ('discount', models.PositiveSmallIntegerField(help_text='Целое число 0–100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('discount__gte', 0), ('discount__lte', 100)), name='discount_between_0_and_100')],
            },
        ),
    ]
